name: GitHub's Super Linter
on: push

jobs
  run-linters:
    name: GitHub's Super Linter
    runs-on: windows
    
    steps: 
      - name: Check out Git repository
        uses: actions/checkout@master
        
      - name: Run GitHub Super Linter
        uses: actions/super-linter@master
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
